spring:
  datasource:
    url: jdbc:mysql://localhost:3307/searchengine?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: usbw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    open-in-view: false

server:
  port: 8081

indexing-settings:
  sites:
    - url: https://dombulgakova.ru
      name: Булгаковский Дом
    - url: http://www.playback.ru
      name: PlayBack.ru

search-bot:
  user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
  referrer: https://www.google.ru
  timeout: 100
